### ISSUE TITLE
space num is disagreement with num in bar

### ISSUE THREAD

**Issue by joytianya** [cmacrae/spacebar#43] opened 2020-11-19 01:59 UTC
![Xnip2020-11-19_09-47-19](https://user-images.githubusercontent.com/17909715/99611005-d3d91600-2a4d-11eb-8d1d-108a4a16a039.jpg)
![Xnip2020-11-19_10-00-39](https://user-images.githubusercontent.com/17909715/99611197-33372600-2a4e-11eb-9b8b-2dbbe477f302.jpg)

![image](https://user-images.githubusercontent.com/17909715/99611050-e5bab900-2a4d-11eb-8cac-ab6b92535bdb.png)

space num is disagreement with num in bar,  and the max index num in bar is one larger than the number of real spaces. I want to know why？Is it my configuration problem?

**Comment by kazhala** [comment] 2020-12-02 03:58
Duplicate of #23, this is not your config problem and perhaps not even spacebar's issue. You will see the same issue even if you install a different space indicating software sadly (e.g. https://github.com/dshnkao/SpaceId)...

**Comment by itgoyo** [comment] 2020-12-09 02:53
@joytianya ,兄弟你是中文的，我就中文和你说吧，因为你没有创建那么多个工作区，你要在skhdrc里面配置
```
# create new space
ctrl - n : yabai -m space --create
```
然后快捷键`ctrl - n`几次，然后就会出现你后面的3、4、5、6、7了，你有时间，试试看效果

**Comment by cmacrae** [comment] 2021-03-31 07:39
Hey @joytianya 👋 Thanks for raising this issue. This has already been reported, so I'll be closing this as a duplicate of #23  
It does seem it's potentially related to the system language, so there are perhaps some hacks I could put in to work around that

**Closed by cmacrae** 2021-03-31 07:39 UTC
Labels: bug, duplicate
